"""Demo account data for Keystone Insurance Group."""
from __future__ import annotations

DEMO_ACCOUNTS = [
    {
        "business_name": "Bella Napoli Italian Restaurant",
        "business_type": "restaurant",
        "naics_code": "722511",
        "address": "245 North Queen Street",
        "city": "Lancaster",
        "state": "PA",
        "zip_code": "17603",
        "annual_revenue": 1_800_000,
        "employee_count": 28,
        "vehicle_count": 2,
        "years_in_business": 18,
        "description": "Full-service Italian restaurant with bar, outdoor patio dining, and growing catering operation. Family-owned, established 2008.",
        "current_policies": [
            {
                "carrier": "Society Insurance",
                "line_of_business": "General Liability",
                "premium": 4200,
                "limits": {"per_occurrence": 1_000_000, "aggregate": 2_000_000},
                "deductibles": {"per_occurrence": 1000},
            },
            {
                "carrier": "Society Insurance",
                "line_of_business": "Property",
                "premium": 6800,
                "limits": {"building": 850_000, "bpp": 250_000, "business_income": 500_000},
                "deductibles": {"all_perils": 2500},
            },
            {
                "carrier": "Society Insurance",
                "line_of_business": "Liquor Liability",
                "premium": 3200,
                "limits": {"per_occurrence": 500_000, "aggregate": 500_000},
                "deductibles": {},
            },
            {
                "carrier": "State Fund",
                "line_of_business": "Workers Compensation",
                "premium": 12500,
                "limits": {"statutory": "PA Statutory"},
                "deductibles": {},
            },
            {
                "carrier": "Society Insurance",
                "line_of_business": "Umbrella",
                "premium": 1800,
                "limits": {"each_occurrence": 1_000_000},
                "deductibles": {},
            },
        ],
    },
    {
        "business_name": "GreenEdge Landscaping",
        "business_type": "landscaping",
        "naics_code": "561730",
        "address": "1180 Paxton Street",
        "city": "Harrisburg",
        "state": "PA",
        "zip_code": "17104",
        "annual_revenue": 950_000,
        "employee_count": 15,
        "vehicle_count": 8,
        "years_in_business": 10,
        "description": "Commercial and residential landscaping with mowing, hardscaping, chemical application, and winter snow removal. Fleet of 6 trucks and 2 trailers.",
        "current_policies": [
            {
                "carrier": "Acuity Insurance",
                "line_of_business": "General Liability",
                "premium": 5600,
                "limits": {"per_occurrence": 1_000_000, "aggregate": 2_000_000},
                "deductibles": {"per_occurrence": 1000},
            },
            {
                "carrier": "Acuity Insurance",
                "line_of_business": "Commercial Auto",
                "premium": 18200,
                "limits": {"csl": 1_000_000},
                "deductibles": {"comprehensive": 1000, "collision": 1000},
            },
            {
                "carrier": "State Fund",
                "line_of_business": "Workers Compensation",
                "premium": 14800,
                "limits": {"statutory": "PA Statutory"},
                "deductibles": {},
            },
            {
                "carrier": "Acuity Insurance",
                "line_of_business": "Inland Marine",
                "premium": 3400,
                "limits": {"scheduled_equipment": 180_000},
                "deductibles": {"per_item": 500},
            },
        ],
    },
    {
        "business_name": "Precision Steel Fabricators",
        "business_type": "manufacturing",
        "naics_code": "332312",
        "address": "4500 Industrial Boulevard",
        "city": "Allentown",
        "state": "PA",
        "zip_code": "18109",
        "annual_revenue": 6_200_000,
        "employee_count": 52,
        "vehicle_count": 5,
        "years_in_business": 25,
        "description": "Precision CNC machining and steel fabrication for industrial, automotive, and defense applications. ISO 9001 certified. 40,000 sq ft facility with 12 CNC machines networked for CAD/CAM.",
        "current_policies": [
            {
                "carrier": "Travelers",
                "line_of_business": "General Liability",
                "premium": 8900,
                "limits": {"per_occurrence": 1_000_000, "aggregate": 2_000_000},
                "deductibles": {"per_occurrence": 2500},
            },
            {
                "carrier": "Travelers",
                "line_of_business": "Property",
                "premium": 22000,
                "limits": {"building": 3_500_000, "bpp": 2_800_000, "business_income": 2_000_000},
                "deductibles": {"all_perils": 5000},
            },
            {
                "carrier": "Travelers",
                "line_of_business": "Products Liability",
                "premium": 15000,
                "limits": {"per_occurrence": 1_000_000, "aggregate": 2_000_000},
                "deductibles": {},
            },
            {
                "carrier": "CNA",
                "line_of_business": "Cyber Liability",
                "premium": 4200,
                "limits": {"aggregate": 250_000},
                "deductibles": {"retention": 10_000},
            },
            {
                "carrier": "State Fund",
                "line_of_business": "Workers Compensation",
                "premium": 38000,
                "limits": {"statutory": "PA Statutory"},
                "deductibles": {},
            },
            {
                "carrier": "Travelers",
                "line_of_business": "Umbrella",
                "premium": 6500,
                "limits": {"each_occurrence": 5_000_000},
                "deductibles": {},
            },
        ],
    },
    {
        "business_name": "Maple Grove Apartments",
        "business_type": "apartment_complex",
        "naics_code": "531110",
        "address": "800 Maple Grove Lane",
        "city": "York",
        "state": "PA",
        "zip_code": "17403",
        "annual_revenue": 1_400_000,
        "employee_count": 6,
        "vehicle_count": 2,
        "years_in_business": 32,
        "description": "48-unit apartment complex built in 1992, renovated 2018. Mix of 1BR and 2BR units. On-site maintenance, tenant screening, and professional property management. 96% occupancy.",
        "current_policies": [
            {
                "carrier": "Philadelphia Insurance (PHLY)",
                "line_of_business": "Property",
                "premium": 18500,
                "limits": {"building": 6_200_000, "bpp": 150_000, "loss_of_rents": 700_000},
                "deductibles": {"all_perils": 5000, "wind_hail": 10_000, "sewer_backup": 25_000},
            },
            {
                "carrier": "Philadelphia Insurance (PHLY)",
                "line_of_business": "General Liability",
                "premium": 4800,
                "limits": {"per_occurrence": 1_000_000, "aggregate": 2_000_000},
                "deductibles": {},
            },
            {
                "carrier": "Philadelphia Insurance (PHLY)",
                "line_of_business": "Umbrella",
                "premium": 2200,
                "limits": {"each_occurrence": 2_000_000},
                "deductibles": {},
            },
            {
                "carrier": "Travelers",
                "line_of_business": "Crime/Fidelity",
                "premium": 1200,
                "limits": {"employee_dishonesty": 100_000},
                "deductibles": {"per_loss": 2500},
            },
        ],
    },
]
